spring:
  banner:
    location: banner-dev.txt
  datasource:
    url: jdbc:h2:tcp://localhost/~/bookCafe
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /resources/
      suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #        show_sql: ture
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


file.dir: \c:\upload\
domain : http://localhost:8080